"""
Create Linear project and tasks from existing meeting data.
Takes the Swedish meeting and generates everything in Linear.
"""
from fastapi import APIRouter, HTTPException
from fastapi.responses import JSONResponse, HTMLResponse
from typing import Dict, List, Optional
from datetime import datetime
from supabase import create_client
from app.config import settings

router = APIRouter(prefix="/linear-sync", tags=["Linear Sync"])


@router.post("/meeting/{meeting_id}")
async def create_linear_from_meeting(meeting_id: str):
    """
    Create Linear project and tasks from existing meeting.
    
    For meeting: "Veckomöte - Team Meeting"
    Creates:
    - Linear project with meeting name
    - All action items as Linear tasks
    - Tasks assigned to correct people
    - Links to meeting view
    """
    
    supabase = create_client(settings.supabase_url, settings.supabase_service_role_key)
    
    # Get meeting data
    meeting_response = supabase.table('meetings').select('*').eq('id', meeting_id).execute()
    if not meeting_response.data:
        raise HTTPException(404, "Meeting not found")
    
    meeting = meeting_response.data[0]
    
    # Get participants
    participants = supabase.table('meeting_participants').select('people(*)').eq('meeting_id', meeting_id).execute()
    attendees = [p['people'] for p in participants.data if p.get('people')]
    
    # Get action items
    actions = supabase.table('action_items').select('*').eq('meeting_id', meeting_id).execute().data
    
    # Get decisions
    decisions = supabase.table('decisions').select('*').eq('meeting_id', meeting_id).execute().data
    
    print("\n" + "=" * 80)
    print(f"CREATING LINEAR PROJECT FROM: {meeting['title']}")
    print("=" * 80)
    print(f"Meeting ID: {meeting_id}")
    print(f"Date: {meeting.get('meeting_date', 'N/A')}")
    print(f"Attendees: {len(attendees)}")
    print(f"Action Items: {len(actions)}")
    print(f"Decisions: {len(decisions)}")
    
    results = {
        'meeting_id': meeting_id,
        'meeting_title': meeting['title'],
        'linear_project': None,
        'linear_tasks': [],
        'errors': []
    }
    
    # Check Linear connection
    if not settings.linear_api_key:
        return JSONResponse({
            "success": False,
            "error": "Linear API key not configured"
        }, status_code=400)
    
    try:
        from app.integrations.linear import get_linear_client
        from gql import gql
        
        client = get_linear_client()
        
        # Get team
        teams = await client.get_teams()
        if not teams:
            raise Exception("No teams found in Linear")
        
        team_id = teams[0]['id']
        team_name = teams[0]['name']
        
        print(f"\nUsing Linear team: {team_name} ({team_id})")
        
        # STEP 1: Create Linear project
        print("\n1. Creating Linear project...")
        
        project_name = f"{meeting['title']} ({meeting.get('meeting_date', datetime.now().strftime('%Y-%m-%d'))})"
        
        project_description = f"""**Meeting:** {meeting['title']}
**Date:** {meeting.get('meeting_date', 'N/A')}
**Attendees:** {', '.join([a.get('name', 'Unknown') for a in attendees])}

**Summary:**
- Attendees: {len(attendees)}
- Decisions: {len(decisions)}
- Action Items: {len(actions)}

**Meeting View:** http://localhost:8000/meeting/{meeting_id}

---
*Auto-generated by Meeting Intelligence Platform*
"""
        
        # Create project using GraphQL
        mutation = gql("""
            mutation CreateProject($input: ProjectCreateInput!) {
                projectCreate(input: $input) {
                    success
                    project {
                        id
                        name
                        url
                    }
                }
            }
        """)
        
        project_result = await client.client.execute_async(
            mutation,
            variable_values={
                "input": {
                    "teamIds": [team_id],
                    "name": project_name,
                    "description": project_description,
                }
            }
        )
        
        linear_project = project_result['projectCreate']['project']
        results['linear_project'] = linear_project
        
        print(f"   ✓ Project created: {linear_project['name']}")
        print(f"   ✓ URL: {linear_project['url']}")
        
        # Store project info in meeting metadata
        current_metadata = meeting.get('meeting_metadata') or {}
        if isinstance(current_metadata, dict):
            current_metadata['linear_project_id'] = linear_project['id']
            current_metadata['linear_project_url'] = linear_project['url']
            
            supabase.table('meetings').update({
                'meeting_metadata': current_metadata
            }).eq('id', meeting_id).execute()
        
        # STEP 2: Create tasks in project
        print(f"\n2. Creating {len(actions)} Linear tasks in project...")
        
        for idx, action in enumerate(actions, 1):
            try:
                task = await _create_linear_task_in_project(
                    client,
                    team_id,
                    linear_project['id'],
                    action,
                    meeting
                )
                
                if task:
                    results['linear_tasks'].append(task)
                    print(f"   ✓ [{idx}/{len(actions)}] {task['identifier']}: {action['title']} → {action.get('owner_name', 'Unassigned')}")
                    
                    # Store Linear task info in action_items table
                    current_action_metadata = action.get('metadata') or {}
                    if isinstance(current_action_metadata, dict):
                        current_action_metadata['linear_issue_id'] = task['id']
                        current_action_metadata['linear_issue_url'] = task['url']
                        current_action_metadata['linear_identifier'] = task['identifier']
                        
                        supabase.table('action_items').update({
                            'metadata': current_action_metadata
                        }).eq('id', action['id']).execute()
                
            except Exception as e:
                error_msg = f"Task creation failed for '{action['title']}': {str(e)}"
                results['errors'].append(error_msg)
                print(f"   ✗ [{idx}/{len(actions)}] {action['title']}: {str(e)}")
        
        print("\n" + "=" * 80)
        print("✅ LINEAR PROJECT & TASKS CREATED")
        print("=" * 80)
        print(f"\n📊 Summary:")
        print(f"  ✓ Project: {linear_project['name']}")
        print(f"  ✓ Tasks created: {len(results['linear_tasks'])}/{len(actions)}")
        print(f"  ✓ Errors: {len(results['errors'])}")
        print(f"\n🔗 Open in Linear:")
        print(f"  {linear_project['url']}")
        
        return {
            "success": True,
            "results": results,
            "message": f"Created Linear project with {len(results['linear_tasks'])} tasks!",
            "open_url": linear_project['url']
        }
        
    except Exception as e:
        print(f"\n✗ Error: {str(e)}")
        results['errors'].append(str(e))
        
        return JSONResponse({
            "success": False,
            "error": str(e),
            "results": results
        }, status_code=500)


async def _create_linear_task_in_project(
    client,
    team_id: str,
    project_id: str,
    action: Dict,
    meeting: Dict
) -> Optional[Dict]:
    """Create a Linear task in the specified project."""
    
    # Build description with context
    description = f"""**From Meeting:** {meeting['title']}
**Date:** {meeting.get('meeting_date', 'N/A')}

{action.get('description', '')}

**Priority:** {action.get('priority', 'medium').upper()}
{f"**Due Date:** {action['due_date']}" if action.get('due_date') else ''}

**Meeting View:** http://localhost:8000/meeting/{meeting['id']}

---
*Auto-generated from meeting action items*
"""
    
    # Map priority
    priority_map = {
        'urgent': 1,
        'high': 2,
        'medium': 3,
        'low': 4
    }
    priority = priority_map.get(action.get('priority', 'medium').lower(), 3)
    
    # Create issue input
    issue_input = {
        "teamId": team_id,
        "projectId": project_id,
        "title": action['title'],
        "description": description,
        "priority": priority,
    }
    
    # Add due date if available
    if action.get('due_date'):
        issue_input["dueDate"] = action['due_date']
    
    # TODO: Add assignee if we have user mapping
    # For now, create unassigned - you can assign manually in Linear
    
    # Create the issue
    issue = await client.create_issue(**issue_input)
    
    return {
        'id': issue['id'],
        'identifier': issue['identifier'],
        'title': issue['title'],
        'url': issue['url'],
        'assignee': action.get('owner_name', 'Unassigned')
    }


@router.get("/ui", response_class=HTMLResponse)
async def linear_sync_ui():
    """UI to sync existing meetings to Linear."""
    
    supabase = create_client(settings.supabase_url, settings.supabase_service_role_key)
    
    # Get all meetings
    meetings = supabase.table('meetings').select('id, title, meeting_date, created_at').order('created_at', desc=True).limit(20).execute()
    
    meetings_html = ""
    for meeting in meetings.data:
        meeting_id = meeting['id']
        title = meeting['title']
        date = meeting.get('meeting_date', 'N/A')
        
        # Check if already synced
        metadata = meeting.get('meeting_metadata') or {}
        has_project = metadata.get('linear_project_id') if isinstance(metadata, dict) else False
        
        status_badge = '<span style="background: #4caf50; color: white; padding: 4px 12px; border-radius: 4px; font-size: 12px;">✓ Synced</span>' if has_project else '<span style="background: #ff9800; color: white; padding: 4px 12px; border-radius: 4px; font-size: 12px;">Not Synced</span>'
        
        meetings_html += f"""
        <div style="background: white; padding: 20px; border-radius: 8px; margin: 12px 0; display: flex; justify-content: space-between; align-items: center; border: 1px solid #e0e0e0;">
            <div>
                <h3 style="margin: 0 0 8px 0; color: #1a1a1a;">{title}</h3>
                <p style="margin: 0; color: #666; font-size: 14px;">Date: {date} | {status_badge}</p>
            </div>
            <button onclick="syncMeeting('{meeting_id}', '{title}')" style="background: linear-gradient(135deg, #0066cc, #00c853); color: white; border: none; padding: 12px 24px; border-radius: 8px; cursor: pointer; font-weight: 600;">
                {'Re-sync' if has_project else 'Create in Linear'}
            </button>
        </div>
        """
    
    html = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Sync Meetings to Linear</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
            background: #f5f5f5;
            margin: 0;
            padding: 20px;
        }}
        .container {{
            max-width: 900px;
            margin: 0 auto;
        }}
        .header {{
            background: linear-gradient(135deg, #0066cc, #00c853);
            color: white;
            padding: 40px;
            border-radius: 12px;
            margin-bottom: 30px;
        }}
        .header h1 {{
            margin: 0 0 10px 0;
        }}
        .result {{
            background: white;
            padding: 20px;
            border-radius: 8px;
            margin: 20px 0;
            display: none;
        }}
        .result.show {{
            display: block;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>📊 Sync Meetings to Linear</h1>
            <p>Create Linear projects and tasks from your meeting data</p>
        </div>
        
        <div id="result" class="result"></div>
        
        <div style="background: white; padding: 30px; border-radius: 12px;">
            <h2 style="margin-top: 0;">Your Meetings</h2>
            {meetings_html if meetings.data else '<p style="color: #999;">No meetings found. Upload a meeting first!</p>'}
        </div>
    </div>
    
    <script>
        async function syncMeeting(meetingId, meetingTitle) {{
            const resultDiv = document.getElementById('result');
            resultDiv.className = 'result show';
            resultDiv.style.background = '#fff3cd';
            resultDiv.innerHTML = `<h3>⏳ Creating Linear project and tasks...</h3><p>Meeting: ${{meetingTitle}}</p>`;
            
            try {{
                const response = await fetch(`/linear-sync/meeting/${{meetingId}}`, {{
                    method: 'POST'
                }});
                
                const data = await response.json();
                
                if (data.success) {{
                    resultDiv.style.background = '#d4edda';
                    resultDiv.innerHTML = `
                        <h3 style="color: #155724;">✅ Success!</h3>
                        <p><strong>Project:</strong> ${{data.results.linear_project.name}}</p>
                        <p><strong>Tasks created:</strong> ${{data.results.linear_tasks.length}}</p>
                        <p><a href="${{data.results.linear_project.url}}" target="_blank" style="color: #0066cc; font-weight: 600;">📊 Open in Linear</a></p>
                        <hr>
                        <details>
                            <summary style="cursor: pointer; color: #0066cc;">Show all tasks</summary>
                            <ul style="margin-top: 12px;">
                                ${{data.results.linear_tasks.map(t => 
                                    `<li><strong>${{t.identifier}}</strong>: ${{t.title}} → ${{t.assignee}}</li>`
                                ).join('')}}
                            </ul>
                        </details>
                    `;
                    
                    // Reload page after 3 seconds to show updated status
                    setTimeout(() => location.reload(), 3000);
                }} else {{
                    resultDiv.style.background = '#f8d7da';
                    resultDiv.innerHTML = `
                        <h3 style="color: #721c24;">❌ Error</h3>
                        <p>${{data.error}}</p>
                    `;
                }}
            }} catch (error) {{
                resultDiv.style.background = '#f8d7da';
                resultDiv.innerHTML = `
                    <h3 style="color: #721c24;">❌ Error</h3>
                    <p>${{error.message}}</p>
                `;
            }}
        }}
    </script>
</body>
</html>
    """
    
    return HTMLResponse(content=html)


@router.get("/swedish-meeting")
async def get_swedish_meeting_for_sync():
    """
    Get the Swedish meeting data for quick sync.
    Returns meeting ID and preview.
    """
    
    supabase = create_client(settings.supabase_url, settings.supabase_service_role_key)
    
    # Find the Swedish meeting
    meetings = supabase.table('meetings').select('id, title, meeting_date').ilike('title', '%Veckomöte%').execute()
    
    if not meetings.data:
        # Try any meeting
        meetings = supabase.table('meetings').select('id, title, meeting_date').order('created_at', desc=True).limit(1).execute()
    
    if not meetings.data:
        return JSONResponse({
            "success": False,
            "error": "No meetings found. Upload a meeting first."
        }, status_code=404)
    
    meeting = meetings.data[0]
    meeting_id = meeting['id']
    
    # Get counts
    actions = supabase.table('action_items').select('id').eq('meeting_id', meeting_id).execute()
    decisions = supabase.table('decisions').select('id').eq('meeting_id', meeting_id).execute()
    
    return {
        "meeting_id": meeting_id,
        "title": meeting['title'],
        "date": meeting.get('meeting_date'),
        "action_items_count": len(actions.data),
        "decisions_count": len(decisions.data),
        "sync_url": f"/linear-sync/meeting/{meeting_id}",
        "quick_command": f"curl -X POST http://localhost:8000/linear-sync/meeting/{meeting_id}"
    }



